name = "xcodedark-theme"
display-name = "Xcode Dark Theme"
description = "Xcode's \"Default (Dark)\" theme."
version = "0.1.1"
author = "JarWarren"
icon = "xcode.png"
repository = "https://github.com/JarWarren/xcodedark-lapce"
color-themes = ["xcodedark.toml"]
